name: CI and Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.x'
      - run: go version

      # Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install dependencies
      - name: Install dependencies
        run: go mod download

      # Run tests
      - name: Run tests
        run: go test ./...

  docker_build:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image to Docker Hub
      - name: Build and push to dockerhub
        uses: docker/build-push-action@v5
        with:
         context: .
         push: true
         tags: gerhardotto/githubaction:latest
